name: 'custom-logs'
description: 'Import- custom logs into Microsoft Sentinel custom tables. Supported file types for sample data are json csv'
inputs:
  filesPath:
    description:  'FileType to import into the workspace.'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
      shell: pwsh
      run: ${{ github.action_path }}/action.ps1 -workspaceId ${{ secrets.WORKSPACEID }} -workspaceKey ${{ secrets.WORKSPACEKEY }} -filesPath ${{ inputs.filesPath }}
