name: 'custom-logs'
description: 'Import- custom logs into Microsoft Sentinel custom tables. Supported file types for sample data are json csv'
inputs:
  filesPath:
    description:  'FileType to import into the workspace.'
    required: false
    default: '.'
  tableName:
    description:  'Name of the custom table to send the data.'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
      shell: pwsh
      env:
        workspaceId: ${{ secrets.workspaceId }}
        workspaceKey: ${{ secrets.workspaceKey }}
      run: |
        ${{ github.action_path }}/action.ps1 -workspaceId $env:workspaceId -workspaceKey $env:workspaceKey -FilesPath ${{ inputs.filesPath }}
