name: 'custom-logs'
description: 'Import custom logs into Microsoft Sentinel custom tables. Supported file types for sample data are json csv'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  filesPath:
    description:  'Folder to import into the workspace.'
    required: false
    default: '.'
  separator:
    description:  'Separator when using multiple paths.'
    required: false
    default: ','
  workspaceId:
    description:  'Workspace Id for the Log Analytics workspace.'
    required: true
    default: '.'
  workspaceKey:
    description:  'Workspace Key for the Log Analytics workspace.'
    required: true
    default: '.'
  tableName:
    description: 'Name of the custom table to save the sample data. If the sample filename ends with _CL a table with the same name will be created!'
    required: false
    default: null

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/action.ps1 `
              -workspaceId  '${{ inputs.WORKSPACEID }}' `
              -workspaceKey '${{ inputs.WORKSPACEKEY }}' `
              -filesPath    '${{ inputs.filesPath }}' `
              -separator    '${{ inputs.separator }}' `
              -tableName    '${{ inputs.tableName}}'
      shell: pwsh
