name: 'custom-logs'
description: 'Import custom logs into Microsoft Sentinel custom tables. Supported file types for sample data are json csv'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  filesPath:
    description:  'FileType to import into the workspace.'
    required: false
    default: '.'
  workspaceId:
    description:  'Workspace Key for Log Analytics workspace.'
    required: true
    default: '.'
  workspaceKey:
    description:  'Workspace Key for Log Analytics workspace.'
    required: true
    default: '.'

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/action.ps1 -workspaceId ${{ inputs.WORKSPACEID }} -workspaceKey ${{ inputs.WORKSPACEKEY }} -filesPath ${{ inputs.filesPath }}
      shell: pwsh
