name: Display Credentials
on: workflow_dispatch

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Debug
      shell: pwsh
      run: |
        Write-Host "Read Secret from variables"
        #$secret1 = "${{ secrets.LONGSECRET }}"
        write-host "workspace ID"
        $newsec = '{0}=-={1}', -f 'secret', "${{ secrets.workspaceid }}"
        
        write-host $newsec
        write-host "secrets variable"
        ${{ secrets }} | convertTo-Json
          
        write-host 'create a file'
        "${{ secrets }}" | out-file 'secrets.json'
          
        write-host $secrets
        write-host 'get-content'
        get-childitem $psscriptroot
        Get-Content ".\secrets.json"
          
        write-host $secrets
        write-host $secrets | ConvertTo-JSON
        $secrets | foreach {
          Write-host $_
        }
        #Write-Host "Generate an error that shows the secret value!!!!"
        #$encodedBytes = [System.Text.Encoding]::UTF8.GetBytes(${{ secrets.LONGSECRET }})
          
      ##  Write-Host 'Set Encoded Bytes'
        #$encodedBytes = [System.Text.Encoding]::UTF8.GetBytes(${{ secrets.LONGSECRET }})
#          Write-Host 'Set Base64'
#          $encodedText = [System.Convert]::ToBase64String($encodedBytes))
