name: Display Credentials
on: workflow_dispatch

jobs:
  secrets-test:
    name: Secrets test
    runs-on: ubuntu-latest
    steps:
      #- name: Check out repository code
      #  uses: actions/checkout@v3
      - name: Perform a test
        shell: pwsh
        run: |
          Write-Host "Read Secret from variables"
          #$secret1 = "${{ secrets.LONGSECRET }}"
          $secrets = "${{ secrets }}"
          
          write-output $secrets
          write-output $secrets | ConvertTo-JSON
          $secrets | foreach {
            Write-output $_
          }
          #Write-Host "Generate an error that shows the secret value!!!!"
          #$encodedBytes = [System.Text.Encoding]::UTF8.GetBytes(${{ secrets.LONGSECRET }})
          
        ##  Write-Host 'Set Encoded Bytes'
          #$encodedBytes = [System.Text.Encoding]::UTF8.GetBytes(${{ secrets.LONGSECRET }})
#          Write-Host 'Set Base64'
#          $encodedText = [System.Convert]::ToBase64String($encodedBytes))
