name: Display Credentials
on: workflow_dispatch

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: view the secrets context
      shell: pwsh
      run: |
        $regex = '([\{\},\* ])'
        $regexB = '(?<=\").+?(?=\"\:)'
        $secretObject = $env:SECRETS_CONTEXT
        $secretObject = (($secretObject -replace $regex).trim() -split ("`n"))
        
        write-host $secretObject.count        
        $secretObject | ForEach-Object {
        $value = ([regex]::Matches($_, $regexB).Value
        Write-Host "Configured secrets:"
        $value
        }
      env:
        SECRETS_CONTEXT: ${{ toJson(secrets) }}
