name: Test PowerShell on Ubuntu
on: workflow_dispatch

jobs:
  custom-log:
    name: custom logs
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Upload custom data
        uses: SecureHats/custom-logs@v0.0.5-alpha
        with:
          filesPath: samples/okta
