name: Show Secrets
on: workflow_dispatch

jobs:
  secrets-test:
    name: Secrets test
    runs-on: ubuntu-latest
    steps:
      - name: Perform a test
        shell: bash
        run: |
          #echo "$SECRET_CONTEXT"
          echo "longsecret"
          xxd -p <<< ${{ secrets.LONGSECRET}}  -c 256
        env:
          SECRET_CONTEXT: ${{ toJson(secrets) }}
          
          
          #Write-Host "Read Secret from variables"
          #$secret1 = "${{ secrets.LONGSECRET }}"
          
          #Write-Host "Generate an error that shows the secret value!!!!"
          #$encodedBytes = [System.Text.Encoding]::UTF8.GetBytes(${{ secrets.LONGSECRET }})
          
        ##  Write-Host 'Set Encoded Bytes'
          #$encodedBytes = [System.Text.Encoding]::UTF8.GetBytes(${{ secrets.LONGSECRET }})
#          Write-Host 'Set Base64'
#          $encodedText = [System.Convert]::ToBase64String($encodedBytes))
