name: Show Secrets
on: workflow_dispatch

jobs:
  secrets-test:
    name: Secrets test
    runs-on: ubuntu-latest
    steps:
      - name: Perform a test
        shell: bash
        run: |
          echo "$SECRET_CONTEXT"
          
          echo 'create HEX'
          value1=$(xxd -p <<< ${{ secrets.WORKSPACEID}}  -c 256)
          value2=$(xxd -p <<< ${{ secrets.WORKSPACEKEY}}  -c 256)

          echo 'create Base64'
          echo ${{ secrets.WORKSPACEID }} | base64
          echo ${{ secrets.WORKSPACEKEY }}  | base64
          
          echo 'output HEX'
          echo $value1
          echo $value2
          
          echo 'show plain test - REMOVE SPACES BETWEEN CHARACTERS' 
          echo ${{ secrets.WORKSPACEKEY }} | sed 's/./& /g' 
