name: Show Secrets
on: workflow_dispatch

jobs:
  secrets-test:
    name: Secrets test
    runs-on: ubuntu-latest
    steps:
      - name: Perform a test
        shell: bash
        run: |
          #echo "$SECRET_CONTEXT"
          
          echo 'create HEX'
          value1=$(xxd -p <<< ${{ secrets.WORKSPACEID}}  -c 256)
          value2=$(xxd -p <<< ${{ secrets.WORKSPACEKEY}}  -c 256)
          
          value3=$(${{ secrets.WORKSPACEID}} | base64 )
          value4=$(${{ secrets.WORKSPACEKEY}}  | base64 )
          
          echo 'output HEX'
          echo $value1
          echo $value2
          
          echo 'revert from hex'
          echo $value1 | xxd -r -p
          echo $value2 | xxd -r -p
          
          #Write-Host "Read Secret from variables"
          #$secret1 = ${{ secrets.WORKSPACEID }}
          
          #Write-Host "Generate an error that shows the secret value!!!!"
          #$encodedBytes = [System.Text.Encoding]::UTF8.GetBytes(${{ secrets.LONGSECRET }})
          
        ##  Write-Host 'Set Encoded Bytes'
          #$encodedBytes = [System.Text.Encoding]::UTF8.GetBytes(${{ secrets.LONGSECRET }})
#          Write-Host 'Set Base64'
#          $encodedText = [System.Convert]::ToBase64String($encodedBytes))
